import type { NextPage } from 'next'
import Head from 'next/head'
import { ToDoContainer } from '../components/ToDoContainer'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const [isClient, setIsClient] = useState(false)
 
  useEffect(() => {
    setIsClient(true)
  }, [])

  return (
    <div 
      style={{background: "linear-gradient(0.125turn, #3f87a6, #ebf8e1, #f69d3c)", 
      height: "100vh",
      display: "flex",
      justifyContent: "center",
      }}
    >
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isClient ? <ToDoContainer /> : "Chargement..."}
    </div>
  )
}

export default Home
